### ISSUE TITLE
Tracking issue for features

### ISSUE THREAD

**Issue by newAM** [newAM/stm32wl-hal#77]
Loose issue to track features I want for my project, may change

Feel free to comment if you want to see features of the HAL not listed here.

* [ ] SUBGHZ https://github.com/newAM/stm32wl-hal/issues/8
  * [ ] async editions of everything
* [ ] RCC
  * [ ] Restrict user control of clocks
* [ ] HSEM
* [ ] IPCC
* [ ] GPIOs
  * [ ] Add all alternate functions
  * [ ] Add `AnyPin` type (maybe?)
  * [ ] Add `async` interface to await a IRQ
* [ ] DMA
  * [ ] mem2mem interface
* [ ] ADC
  * [x] Junction temperature measurement
  * [ ] Battery level measurement
* [x] RNG
* [x] AES
    * [x] ECB
* [x] PKA
     * [x] ECDSA sign
     * [x] ECDSA verify
* [ ] Timers
* [ ] RTC
* [ ] I2C
* [ ] UART
* [x] SPI
    * [x] device main
    * [x] async API (DMA only)
* [x] electronic signature

**Comment by newAM** [comment]
Going to close this and track this in a per-peripheral issue.
