### ISSUE TITLE
Tracking issue for SubGHz commands

### ISSUE THREAD

**Issue by newAM** [newAM/stm32wl-hal#8]
### 5.8.2 Register and Buffer Access

* [x] `Read_Buffer`
* [x] `Write_Buffer`

#### Registers

Implementing all these instead of the generic `Read_Register` and `Write_Register` commands.

* [x] `SUBGHZ_GBSYNCR` - #169 
* [x] `SUBGHZ_GPKTCTL1AR` - #170 
* [x] `SUBGHZ_GWHITEINIRL`
* [x] `SUBGHZ_GCRCINIR[H/L]`
* [x] `SUBGHZ_GCRCPOLR[H/L]`
* [x] `SUBGHZ_GSYNCR[0-7]`
* [x] `SUBGHZ_LSYNCR[H/L]`
* [x] `SUBGHZ_RNGR[0-3]` - skip because we have TRNG peripheral
* [x] `SUBGHZ_RXGAINCR` - #166 
* [x] `SUBGHZ_PAOCPR`
* [x] `SUBGHZ_HSEINTRIMR`
* [x] `SUBGHZ_HSEOUTTRIMR`
* [x] `SUBGHZ_SMPSC0R`- #171 
* [x] `SUBGHZ_PCR` - #173 
* [x] `SUBGHZ_SMPSC2R` - #172

### 5.8.3 Operating Mode Commands

* [x] `Set_Sleep`
* [x] `Set_Standby`
* [x] `Set_Fs`
* [x] `Set_Tx`
* [x] `Set_Rx`
* [x] `Set_StopRxTimerOnPreamble`
* [x] `Set_RxDutyCycle`
* [x] `Set_Cad`
* [x] `Set_TxContinuousWave`
* [x] `Set_TxContinuousPreamble`

### 5.8.4 Sub-GHz radio configuration commands

* [x] `Set_PacketType`
* [x] `Get_PacketType`
* [x] `Set_RfFrequency`
* [x] `Set_TxParams`
* [x] `Set_PaConfig`
* [x] `Set_TxRxFallbackMode`
* [x] `Set_CadParams`
* [x] `Set_BufferBaseAddress`
* [x] (G)FSK `Set_ModulationParams`
* [x] LoRa `Set_ModulationParams`
* [x] BPSK `Set_ModulationParams`
* [x] Generic `Set_PacketParams`
* [x] BPSK `Set_PacketParams`
* [x] LoRa `Set_PacketParams`
* [x] `Set_LoRaSymbTimeout`

### 5.8.5 Communication status and information commands

* [x] `Get_Status`
* [x] `Get_RxBufferStatus`
* [x] (G)FSK `Get_PacketStatus`
* [x] LoRa `Get_PacketStatus`
* [x] `Get_RssiInst`
* [x] (G)FSK `Get_Stats`
* [x] LoRa `Get_Stats`
* [x] `Reset_Stats`

### 5.8.6 IRQ interrupt commands

* [x] `Cfg_DioIrq`
* [x] `Get_IrqStatus`
* [x] `Clr_IrqStatus`

### 5.8.7 Miscellaneous commands

* [x] `Calibrate`
* [x] `CalibrateImage`
* [x] `Set_RegulatorMode`
* [x] `Get_Error`
* [x] `Clr_Error`

### 5.8.8 Set_TcxoMode command

* [x] `Set_TcxoMode`
